#!/usr/bin/env node
/**
 * ClawEnvKit MCP Server
 *
 * Reads /tmp/eval-tools.json (generated by entrypoint from OpenAPI spec)
 * and exposes each mock-service endpoint as an MCP tool.
 *
 * Works with: Claude Code, Codex, Cursor, Windsurf, Continue, and any
 * MCP-compatible agent.
 *
 * Usage:
 *   EVAL_TOOLS_FILE=/tmp/eval-tools.json node index.js
 *
 * Or via Claude Code config:
 *   "mcpServers": {
 *     "clawenvkit": {
 *       "command": "node",
 *       "args": ["/opt/clawenvkit/mcp_server/index.js"]
 *     }
 *   }
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import * as fs from "node:fs";
import * as http from "node:http";

const TOOLS_FILE = process.env.EVAL_TOOLS_FILE || "/tmp/eval-tools.json";

// ---------------------------------------------------------------------------
// HTTP helper — direct localhost call to mock service
// ---------------------------------------------------------------------------

function makeRequest(port, path, method, body) {
  return new Promise((resolve, reject) => {
    const req = http.request(
      {
        hostname: "127.0.0.1",
        port,
        path,
        method: method.toUpperCase(),
        headers: { "Content-Type": "application/json" },
      },
      (res) => {
        let data = "";
        res.on("data", (chunk) => (data += chunk));
        res.on("end", () => {
          try {
            resolve(JSON.parse(data));
          } catch {
            resolve({ raw: data });
          }
        });
      },
    );
    req.on("error", reject);
    req.setTimeout(30_000, () => req.destroy(new Error("Request timeout")));
    if (body !== undefined && body !== null) {
      req.write(JSON.stringify(body));
    }
    req.end();
  });
}

// ---------------------------------------------------------------------------
// OpenAPI property → Zod schema (MCP SDK uses Zod, not TypeBox)
// ---------------------------------------------------------------------------

function openApiPropToZod(key, schema, required) {
  const isRequired = required.includes(key);

  // Handle Pydantic nullable: anyOf: [{type: "string"}, {type: "null"}]
  let effectiveType = schema.type;
  if (schema.anyOf) {
    const nonNull = schema.anyOf.find((s) => s.type !== "null");
    if (nonNull) effectiveType = nonNull.type;
  }

  let zodType;
  switch (effectiveType) {
    case "string":
      zodType = z.string().describe(schema.title || key);
      break;
    case "integer":
    case "number":
      zodType = z.number().describe(schema.title || key);
      break;
    case "boolean":
      zodType = z.boolean().describe(schema.title || key);
      break;
    case "array":
      zodType = z.array(z.string()).describe(schema.title || key);
      break;
    default:
      zodType = z.string().describe(schema.title || key);
  }

  return isRequired ? zodType : zodType.optional();
}

function buildZodSchema(toolDef) {
  const shape = {};
  const required = toolDef.required || [];

  for (const [key, schema] of Object.entries(toolDef.parameters || {})) {
    shape[key] = openApiPropToZod(key, schema, required);
  }

  return z.object(shape);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  // Read tool definitions
  if (!fs.existsSync(TOOLS_FILE)) {
    console.error(`[clawenvkit-mcp] No tools file at ${TOOLS_FILE}`);
    console.error("[clawenvkit-mcp] Run the entrypoint first to generate eval-tools.json");
    process.exit(1);
  }

  let tools;
  try {
    tools = JSON.parse(fs.readFileSync(TOOLS_FILE, "utf8"));
  } catch (err) {
    console.error(`[clawenvkit-mcp] Failed to read tools: ${err.message}`);
    process.exit(1);
  }

  if (!Array.isArray(tools) || tools.length === 0) {
    console.error("[clawenvkit-mcp] No tools defined in eval-tools.json");
    process.exit(1);
  }

  // Create MCP server
  const server = new McpServer({
    name: "clawenvkit",
    version: "0.0.1",
  });

  // Register each mock-service endpoint as an MCP tool
  for (const toolDef of tools) {
    const zodSchema = buildZodSchema(toolDef);

    server.tool(
      toolDef.name,
      toolDef.description,
      zodSchema.shape,
      async (args) => {
        try {
          const result = await makeRequest(
            toolDef.port,
            toolDef.endpoint,
            toolDef.method,
            args,
          );
          return {
            content: [
              { type: "text", text: JSON.stringify(result, null, 2) },
            ],
          };
        } catch (err) {
          return {
            content: [
              { type: "text", text: `Error calling ${toolDef.name}: ${err.message}` },
            ],
            isError: true,
          };
        }
      },
    );
  }

  console.error(`[clawenvkit-mcp] Registered ${tools.length} tools`);

  // Connect via stdio transport
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("[clawenvkit-mcp] Server running on stdio");
}

main().catch((err) => {
  console.error(`[clawenvkit-mcp] Fatal: ${err.message}`);
  process.exit(1);
});
